/**
 * Icon sprite builder
 * -----------------------------------------------------------------------------
 * Reads every SVG in src/assets/icons/ and emits a single <symbol> sprite at
 * public/icons.svg.
 *
 * WHY THIS EXISTS
 * Icons exported from Figma are not usable as-is:
 *   1. They carry a hardcoded stroke colour (e.g. stroke="#667085"), so they
 *      cannot inherit text colour and would need a variant per colour.
 *   2. Their viewBox is the path's bounding box (e.g. "0 0 20 22"), not the
 *      24x24 frame it was drawn in, so icons render at inconsistent sizes.
 *   3. They carry preserveAspectRatio="none" and inline styles from the export.
 *
 * This script fixes all three, so a raw Figma export can be dropped into
 * src/assets/icons/ unmodified.
 *
 * ADDING AN ICON
 *   1. Export the SVG from Figma into src/assets/icons/<kebab-name>.svg
 *   2. npm run icons
 *   3. Use it: <Icon name="<kebab-name>" />
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "src/assets/icons");
const OUT = join(root, "public/icons.svg");

/**
 * Fraction of the square grid the artwork should occupy.
 * Matches the 8.33% inset Untitled UI uses when drawing a 24px icon, so the
 * sprite reproduces the optical weight seen in Figma.
 */
const CONTENT_RATIO = 0.833;

function normalise(svg, name) {
  // --- viewBox -> centred, optically-normalised square ------------------------
  const vb = svg.match(/viewBox="([^"]+)"/);
  if (!vb) throw new Error(`${name}.svg has no viewBox`);

  const [minX, minY, w, h] = vb[1].trim().split(/[\s,]+/).map(Number);
  if ([minX, minY, w, h].some(Number.isNaN)) {
    throw new Error(`${name}.svg has a malformed viewBox: "${vb[1]}"`);
  }

  // Figma exports the path's bounding box, not the frame it was drawn in, so a
  // 12px badge arrow and a 24px nav icon arrive with wildly different extents.
  // Scaling the square to the artwork (rather than to a fixed 24 grid) makes
  // every icon fill the same proportion of its box, whatever its origin.
  const side = Math.max(w, h) / CONTENT_RATIO;
  const x = minX - (side - w) / 2;
  const y = minY - (side - h) / 2;
  const viewBox = `${round(x)} ${round(y)} ${round(side)} ${round(side)}`;

  // --- body ------------------------------------------------------------------
  let body = svg
    .replace(/^[\s\S]*?<svg[^>]*>/i, "")
    .replace(/<\/svg>\s*$/i, "")
    .trim();

  // Hardcoded colours -> currentColor, so one icon serves every text colour.
  // Figma emits these as hex ("#667085") AND as CSS keywords ("white"), so
  // match any value and let "none" through - that one is structural, not a
  // colour, and dropping it would fill every outline icon solid.
  const recolour = (attr) => (match, value) =>
    value.trim().toLowerCase() === "none" ? match : `${attr}="currentColor"`;

  body = body
    .replace(/stroke="([^"]*)"/g, recolour("stroke"))
    .replace(/fill="([^"]*)"/g, recolour("fill"));

  // Export artefacts that break sizing.
  body = body
    .replace(/\spreserveAspectRatio="[^"]*"/g, "")
    .replace(/\sstyle="[^"]*"/g, "");

  // Stroke weight is authored against the source frame (2 on a 24px nav icon,
  // 1.5 on a 12px badge icon). Once each icon is scaled to its own square those
  // raw values read as inconsistent, so restate them relative to the new box:
  // 2 units on a 24 grid.
  const strokeWidth = round(side / 12);
  body = body.replace(/\sstroke-width="[^"]*"/g, ` stroke-width="${strokeWidth}"`);

  // Figma names every path id="Icon"; duplicated across symbols that is invalid.
  body = body.replace(/\sid="[^"]*"/g, "");

  return { viewBox, body };
}

const round = (n) => (Number.isInteger(n) ? n : Number(n.toFixed(3)));

// --- build -------------------------------------------------------------------

const files = readdirSync(SRC)
  .filter((f) => f.endsWith(".svg"))
  .sort();

if (files.length === 0) {
  console.error(`No SVGs found in ${SRC}`);
  process.exit(1);
}

const symbols = [];
const names = [];

for (const file of files) {
  const name = basename(file, ".svg");
  const { viewBox, body } = normalise(readFileSync(join(SRC, file), "utf8"), name);
  symbols.push(
    `  <symbol id="${name}" viewBox="${viewBox}" fill="none" ` +
      `stroke-linecap="round" stroke-linejoin="round">\n` +
      body.split("\n").map((l) => `    ${l.trim()}`).join("\n") +
      `\n  </symbol>`
  );
  names.push(name);
}

const sprite =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- GENERATED by scripts/build-icons.mjs - do not edit by hand. -->\n` +
  `<!-- Source: src/assets/icons/*.svg (exported from Figma FINAL SCREENS) -->\n` +
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n` +
  symbols.join("\n") +
  `\n</svg>\n`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, sprite, "utf8");

// Emit the name list so the Icon component can validate against it.
const registry =
  `// GENERATED by scripts/build-icons.mjs — do not edit by hand.\n` +
  `export const ICON_NAMES = [\n` +
  names.map((n) => `  "${n}",`).join("\n") +
  `\n];\n`;

writeFileSync(join(root, "src/components/ui/icon-names.js"), registry, "utf8");

console.log(`✓ ${names.length} icons → public/icons.svg`);
console.log(`  ${names.join(", ")}`);
